services:
  - type: web
    name: rocha-trindade-total-v22-4
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: RENDER_DISK_PATH
        value: /opt/render/project/src/.sistemaX
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          property: renderURL
